### ISSUE TITLE
kar-scheduler pod panic when deployed on  IBM Cloud Private  2.1.0.3

### ISSUE THREAD

**Issue by khahmed** [kubernetes-retired/kube-batch#273]
I tried installing the latest kube-arbitrator from helm chart in IBM Cloud Private  2.1.0.3. ICP 2.1.0.3 has K8S 1.10/Helm 2.7.3. I find that kube scheduler has a panic. 

~~~
Khalids-MacBook-Pro:deployment khalida$ helm install kube-arbitrator --namespace kube-system --tls
NAME:   orderly-warthog
LAST DEPLOYED: Fri Jul  6 09:02:50 2018
NAMESPACE: kube-system
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/Deployment
NAME             DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
kar-scheduler    1        1        1           0          1s
kar-controllers  1        1        1           0          1s

==> v1/Pod(related)
NAME                             READY  STATUS             RESTARTS  AGE
kar-scheduler-689d49fdb8-k6bdd   0/1    ContainerCreating  0         1s
kar-controllers-bb9dcb65b-mll4s  0/1    ContainerCreating  0         1s


NOTES:
~~~

~~~
$ kubectl logs kar-scheduler-689d49fdb8-k6bdd -n kube-system
E0706 13:04:42.613642       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:502
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:388
/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/client-go/tools/cache/controller.go:224
/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:554
/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203
/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203
/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:548
/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:546
/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:390
/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/usr/local/go/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa1bdb5]

goroutine 44 [running]:
github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0xfae620, 0x18ed3a0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnAdd(0x0, 0x11effc0, 0xc42032c780, 0x10de3e0, 0xc420148140)
	/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/client-go/tools/cache/controller.go:224 +0x35
github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x0, 0x0, 0x0)
	/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:554 +0x21a
github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0xc42061fdf0, 0x429e39, 0xc42032f390)
	/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203 +0x9c
github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:548 +0x81
github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4202f5768)
	/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc42061ff68, 0xdf8475800, 0x0, 0xf8bf01, 0xc4200f9020)
	/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4202f5768, 0xdf8475800, 0xc4200f9020)
	/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc420322e00)
	/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:546 +0x78
github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/client-go/tools/cache.(*processorListener).(github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/client-go/tools/cache.run)-fm()
	/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:390 +0x2a
github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc42031b9c0, 0xc420380c80)
	/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/k82cn/go_ws/src/github.com/kubernetes-incubator/kube-arbitrator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
~~~

~~~
Khalids-MacBook-Pro:deployment khalida$ helm version --tls
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.3+icp", GitCommit:"27442e4cfd324d8f82f935fe0b7b492994d4c289", GitTreeState:"dirty"}
Khalids-MacBook-Pro:deployment khalida$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0+icp", GitCommit:"1c6988c2361d678dab8ea5ddfab82cb52680b20b", GitTreeState:"clean", BuildDate:"2018-04-27T05:47:17Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
~~~

**Comment by k82cn** [comment]
This should be fixed by #278 , client-go did not ignore `FilterFunc` if using `FilteringResourceEventHandler`; so the PR uses `ResourceEventHandlerFuncs` as fix.
