### ISSUE TITLE
Observed a panic: "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by zhuhesheng** [kubernetes-retired/kube-batch#853]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
```
I0516 04:37:06.887104       1 scheduler_helper.go:38] Considering Task <default/batch-1-p-w-2-cbtvn> on node <ip-10-0-7-61.ec2.internal>: <cpu 1500.00, memory 3670016000.00, GPU 0.00> vs. <cpu 1890.00, memory 3782279168.00, GPU 0.00>
I0516 04:37:06.887142       1 scheduler_helper.go:38] Considering Task <default/batch-1-p-w-2-cbtvn> on node <ip-10-0-19-145.ec2.internal>: <cpu 1500.00, memory 3670016000.00, GPU 0.00> vs. <cpu 1890.00, memory 3782279168.00, GPU 0.00>
E0516 04:37:06.887314       1 scheduler_helper.go:43] Predicates failed for task <default/batch-1-p-w-2-cbtvn> on node <ip-10-0-19-145.ec2.internal>: task <default/batch-1-p-w-2-cbtvn> does not tolerate node <ip-10-0-19-145.ec2.internal> taints
I0516 04:37:06.887162       1 scheduler_helper.go:38] Considering Task <default/batch-1-p-w-2-cbtvn> on node <ip-10-0-2-157.ec2.internal>: <cpu 1500.00, memory 3670016000.00, GPU 0.00> vs. <cpu 1900.00, memory 3782279168.00, GPU 0.00>
E0516 04:37:06.887334       1 scheduler_helper.go:43] Predicates failed for task <default/batch-1-p-w-2-cbtvn> on node <ip-10-0-2-157.ec2.internal>: task <default/batch-1-p-w-2-cbtvn> does not tolerate node <ip-10-0-2-157.ec2.internal> taints
I0516 04:37:06.887195       1 scheduler_helper.go:38] Considering Task <default/batch-1-p-w-2-cbtvn> on node <ip-10-0-21-200.ec2.internal>: <cpu 1500.00, memory 3670016000.00, GPU 0.00> vs. <cpu 1890.00, memory 3782279168.00, GPU 0.00>
E0516 04:37:06.887385       1 scheduler_helper.go:43] Predicates failed for task <default/batch-1-p-w-2-cbtvn> on node <ip-10-0-21-200.ec2.internal>: task <default/batch-1-p-w-2-cbtvn> does not tolerate node <ip-10-0-21-200.ec2.internal> taints
E0516 04:37:06.887553       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:522
/usr/local/go/src/runtime/panic.go:513
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/kubernetes/pkg/scheduler/cache/node_info.go:611
/root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/plugins/nodeorder/nodeorder.go:66
/root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/plugins/nodeorder/nodeorder.go:243
/root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/framework/session_plugins.go:364
/root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/actions/allocate/allocate.go:148
/root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/util/scheduler_helper.go:64
/root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:65
/usr/local/go/src/runtime/asm_amd64.s:1333
I0516 04:37:06.887857       1 asm_amd64.s:523] Leaving Allocate ...
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x168 pc=0x10ad54d]

goroutine 61624 [running]:
github.com/kubernetes-sigs/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x126a4a0, 0x21a4e50)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/kubernetes-sigs/volcano/vendor/k8s.io/kubernetes/pkg/scheduler/cache.(*NodeInfo).SetNode(0xc000511790, 0x0, 0x0, 0xc000511790)
        /root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/kubernetes/pkg/scheduler/cache/node_info.go:611 +0x3d
github.com/kubernetes-sigs/volcano/pkg/scheduler/plugins/nodeorder.generateNodeMapAndSlice(0xc0005cc4b0, 0xc000486180, 0x1, 0x1, 0x1)
        /root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/plugins/nodeorder/nodeorder.go:66 +0x12b
github.com/kubernetes-sigs/volcano/pkg/scheduler/plugins/nodeorder.(*nodeOrderPlugin).OnSessionOpen.func1(0xc000429700, 0xc0008f40a0, 0xc0006061c0, 0x9, 0xc0006f9338)
        /root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/plugins/nodeorder/nodeorder.go:243 +0x12e
github.com/kubernetes-sigs/volcano/pkg/scheduler/framework.(*Session).NodeOrderFn(0xc0003c60e0, 0xc000429700, 0xc0008f40a0, 0xc000826738, 0x4058f1, 0xc00090a058)
        /root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/framework/session_plugins.go:364 +0x1bd
github.com/kubernetes-sigs/volcano/pkg/scheduler/framework.(*Session).NodeOrderFn-fm(0xc000429700, 0xc0008f40a0, 0x0, 0x0, 0xc000077b00)
        /root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/actions/allocate/allocate.go:148 +0x3e
github.com/kubernetes-sigs/volcano/pkg/scheduler/util.PrioritizeNodes.func1(0x0)
        /root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/util/scheduler_helper.go:64 +0x7f
github.com/kubernetes-sigs/volcano/vendor/k8s.io/client-go/util/workqueue.ParallelizeUntil.func1(0xc0006c0720, 0xc00090a000, 0xc000486168, 0xc000780840)
        /root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:65 +0x91
created by github.com/kubernetes-sigs/volcano/vendor/k8s.io/client-go/util/workqueue.ParallelizeUntil
        /root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:57 +0x148
```

**What you expected to happen**:
no err
**How to reproduce it (as minimally and precisely as possible)**:

**job reach podGroup minMember**

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:  aws eks 
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`): 
- Install tools: eks
- Others:

**Comment by k82cn** [comment]
@thandayuthapani , would you help to check this one?

**Comment by thandayuthapani** [comment]
@zhuhesheng Can you specify which version of kube-batch was used? Or git commit of kube-batch!
With latest code I was not able to reporduce that panic? Can you try with latest code and see whether you are facing that problem? Or give details about how to reproduce it.

**Comment by zhuhesheng** [comment]
> My Version: v0.4.2 

> install command:
```
# mkdir -p $GOPATH/src/github.com/kubernetes-sigs/
# cd $GOPATH/src/github.com/kubernetes-sigs/
# git clone http://github.com/kubernetes-sigs/kube-batch -b v0.4.2
```
> cloud: aws eks

> aws auto scaling group(current 1,max 5),(Node: 2C4G)

> My PodGroup：
```
apiVersion: scheduling.incubator.k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: batch-1-w-2
spec:
  minMember: 3
  Queue: "weight-2"
```

> My Queue
```
apiVersion: scheduling.incubator.k8s.io/v1alpha1
kind: Queue
metadata:
  name: weight-2
spec:
  weight: 2
```

> My Job
```
apiVersion: batch/v1
kind: Job
metadata:
  name: batch-1-p-w-2
spec:
  backoffLimit: 6
  completions: 4
  parallelism: 4
  template:
    metadata:
      annotations:
        scheduling.k8s.io/group-name: batch-1-w-2
    spec:
      containers:
      - image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        command: ["sh","-c","sleep 300"]
        resources:
          requests:
            cpu: "1.5"
            memory: 3500Mi
      restartPolicy: Never
      schedulerName: kube-batch
```

> After Apply -f, The above error occurred

**Comment by zhuhesheng** [comment]
@thandayuthapani

**Comment by TommyLike** [comment]
@thandayuthapani considering if there is a delay when collecting our cluster nodes info, we would assembly our cache's NodeInfo with `*v1.Node` is nil,  and this would lead to the nil pointer issue:
```
func (sc *SchedulerCache) addTask(pi *kbapi.TaskInfo) error {
	job := sc.getOrCreateJob(pi)
	if job != nil {
		job.AddTaskInfo(pi)
	}

	if len(pi.NodeName) != 0 {
		if _, found := sc.Nodes[pi.NodeName]; !found {
			sc.Nodes[pi.NodeName] = kbapi.NewNodeInfo(nil)   //here
		}

		node := sc.Nodes[pi.NodeName]
		if !isTerminated(pi.Status) {
			return node.AddTask(pi)
		}
	}

	return nil
}
```
But this is what I infered by reading the code, hope it helps.

**Comment by thandayuthapani** [comment]
@TommyLike Thank You for your inference.  I think the same, if there is delay in collection *v1.Node info from cluster.  But I was not able to replicate the exact behaviour in my environment, after running multiple times, @zhuhesheng did you face same panic again? Since with your infos and examples provided, I was not facing that panic problem.

**Comment by k82cn** [comment]
Not sure whether share the same root cause with https://github.com/kubernetes-sigs/kube-batch/issues/861 ; we I think you can try https://github.com/kubernetes-sigs/kube-batch/pull/860 firstly.

**Comment by Cplo** [comment]
I also reproduced the above bug here.
```
E0617 21:57:03.824948       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:522
/usr/local/go/src/runtime/panic.go:513
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/kubernetes/pkg/scheduler/cache/node_info.go:611
/root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/plugins/nodeorder/nodeorder.go:66
/root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/plugins/nodeorder/nodeorder.go:243
/root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/framework/session_plugins.go:364
/root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/actions/allocate/allocate.go:148
/root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/util/scheduler_helper.go:64
/root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:65
/usr/local/go/src/runtime/asm_amd64.s:1333
I0617 21:57:03.825565       1 asm_amd64.s:523] Leaving Allocate ...
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x168 pc=0x10ad54d]

goroutine 99856 [running]:
github.com/kubernetes-sigs/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x126a4a0, 0x21a4e50)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/kubernetes-sigs/volcano/vendor/k8s.io/kubernetes/pkg/scheduler/cache.(*NodeInfo).SetNode(0xc002fe3c70, 0x0, 0x0, 0xc002fe3c70)
	/root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/kubernetes/pkg/scheduler/cache/node_info.go:611 +0x3d
github.com/kubernetes-sigs/volcano/pkg/scheduler/plugins/nodeorder.generateNodeMapAndSlice(0xc003b8a180, 0xc0025c4060, 0x1, 0x1, 0x1)
	/root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/plugins/nodeorder/nodeorder.go:66 +0x12b
github.com/kubernetes-sigs/volcano/pkg/scheduler/plugins/nodeorder.(*nodeOrderPlugin).OnSessionOpen.func1(0xc001960e00, 0xc0030908c0, 0xc0022ba170, 0x9, 0xc002590b18)
	/root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/plugins/nodeorder/nodeorder.go:243 +0x12e
github.com/kubernetes-sigs/volcano/pkg/scheduler/framework.(*Session).NodeOrderFn(0xc0024256c0, 0xc001960e00, 0xc0030908c0, 0xc001860738, 0x4058f1, 0xc0028f6058)
	/root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/framework/session_plugins.go:364 +0x1bd
github.com/kubernetes-sigs/volcano/pkg/scheduler/framework.(*Session).NodeOrderFn-fm(0xc001960e00, 0xc0030908c0, 0x0, 0x0, 0xc0027fa600)
	/root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/actions/allocate/allocate.go:148 +0x3e
github.com/kubernetes-sigs/volcano/pkg/scheduler/util.PrioritizeNodes.func1(0x7)
	/root/asif/go/src/github.com/kubernetes-sigs/volcano/pkg/scheduler/util/scheduler_helper.go:64 +0x7f
github.com/kubernetes-sigs/volcano/vendor/k8s.io/client-go/util/workqueue.ParallelizeUntil.func1(0xc002079370, 0xc0028f6000, 0xc0005a6070, 0xc0029605c0)
	/root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:65 +0x91
created by github.com/kubernetes-sigs/volcano/vendor/k8s.io/client-go/util/workqueue.ParallelizeUntil
	/root/asif/go/src/github.com/kubernetes-sigs/volcano/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:57 +0x148
```

version: v0.4.2

**It is worth noting that two k8s nodes were removed at that point in time.(hardware fault
)**
